<?php
defined( 'ABSPATH' ) || die();

return [
	[
		'id'       => 'email_reports_mailinglist',
		'menu_id'  => 'reports',
		'group_id' => 'reports',
		'type'     => 'email_reports',
		'label'    => __( 'Email reports', 'burst-statistics' ),
		'disabled' => false,
		'default'  => '',
	],
	[
		'id'            => 'logo_attachment_id',
		'menu_id'       => 'customization',
		'group_id'      => 'customization',
		'type'          => 'image_picker',
		'label'         => __( 'Change logo in the email reports', 'burst-statistics' ),
		'context'       => __( 'Recommended size is 200 pixels by 70 pixels and try to keep the filesize under 200 kb.', 'burst-statistics' ),
		'media_title'   => __( 'Select logo', 'burst-statistics' ),
		'media_button'  => __( 'Set logo', 'burst-statistics' ),
		'default_image' => BURST_URL . 'assets/img/burst-email-logo.png',
		'pro'           => [
			'url' => 'pricing/',
		],
		'disabled'      => false,
		'default'       => false,
	],
	[
		'id'            => 'hero_background_image_attachment_id',
		'menu_id'       => 'customization',
		'group_id'      => 'customization',
		'type'          => 'image_picker',
		'label'         => __( 'Background image for hero', 'burst-statistics' ),
		'context'       => __( 'This image will be used as the background of the hero section in email reports.', 'burst-statistics' ),
		'media_title'   => __( 'Select background image', 'burst-statistics' ),
		'media_button'  => __( 'Set background image', 'burst-statistics' ),
		'default_image' => BURST_URL . 'assets/img/burst-report-hero-bg.jpg',
		'color_overlay' => [
			'color'   => 'brand_color',
			'enabled' => 'hero_color_overlay_enabled',
		],
		'pro'           => [
			'url'  => 'pricing/',
			'tier' => 'agency',
		],
		'disabled'      => false,
		'default'       => false,
	],
	[
		'id'       => 'hero_color_overlay_enabled',
		'menu_id'  => 'customization',
		'group_id' => 'customization',
		'type'     => 'checkbox',
		'label'    => __( 'Show colour overlay on hero background', 'burst-statistics' ),
		'context'  => __( 'Apply the brand colour as an overlay on the hero background image.', 'burst-statistics' ),
		'pro'      => [
			'url'  => 'pricing/',
			'tier' => 'agency',
		],
		'disabled' => false,
		'default'  => true,
	],
	[
		'id'       => 'brand_color',
		'menu_id'  => 'customization',
		'group_id' => 'customization',
		'type'     => 'color_picker',
		'label'    => __( 'Brand color', 'burst-statistics' ),
		'context'  => __( 'Select your brand color for the email reports.', 'burst-statistics' ),
		'pro'      => [
			'url'  => 'pricing/',
			'tier' => 'agency',
		],
		'disabled' => false,
		'default'  => '#2B8133',
	],
	[
		'id'       => 'email_introduction_enabled',
		'menu_id'  => 'customization',
		'group_id' => 'email',
		'type'     => 'checkbox',
		'label'    => __( 'Custom email introduction', 'burst-statistics' ),
		'context'  => __( 'Enable to add a custom introduction to the email reports. When disabled, no introduction is shown.', 'burst-statistics' ),
		'pro'      => [
			'url'  => 'pricing/',
			'tier' => 'agency',
		],
		'disabled' => false,
		'default'  => false,
	],
	[
		'id'               => 'email_introduction',
		'menu_id'          => 'customization',
		'group_id'         => 'email',
		'type'             => 'wysiwyg',
		'label'            => __( 'Email introduction', 'burst-statistics' ),
		'context'          => __( 'This text will be added as an introduction to the email reports.', 'burst-statistics' ),
		'pro'              => [
			'url'  => 'pricing/',
			'tier' => 'agency',
		],
		'disabled'         => false,
		'default'          => false,
		'react_conditions' => [
			'email_introduction_enabled' => true,
		],
	],
	[
		'id'       => 'email_footer_enabled',
		'menu_id'  => 'customization',
		'group_id' => 'email',
		'type'     => 'checkbox',
		'label'    => __( 'Custom email footer', 'burst-statistics' ),
		'context'  => __( 'Enable to replace the default footer with a custom one. When disabled, the default footer is used.', 'burst-statistics' ),
		'pro'      => [
			'url'  => 'pricing/',
			'tier' => 'agency',
		],
		'disabled' => false,
		'default'  => false,
	],
	[
		'id'               => 'email_footer',
		'menu_id'          => 'customization',
		'group_id'         => 'email',
		'type'             => 'wysiwyg',
		'label'            => __( 'Email footer', 'burst-statistics' ),
		'context'          => __( 'This text will be added to the footer of the email reports.', 'burst-statistics' ),
		'pro'              => [
			'url'  => 'pricing/',
			'tier' => 'agency',
		],
		'disabled'         => false,
		'default'          => false,
		'react_conditions' => [
			'email_footer_enabled' => true,
		],
	],
	[
		'id'       => 'report_logs',
		'menu_id'  => 'logs',
		'group_id' => 'logs',
		'type'     => 'report_logs',
		'label'    => __( 'Email report logs', 'burst-statistics' ),
		'disabled' => false,
		'default'  => false,
	],
];
