<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'swentel\\nostr\\' => array($vendorDir . '/swentel/nostr-php/src'),
    'WebSocket\\' => array($vendorDir . '/phrity/websocket/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Phrity\\Util\\' => array($vendorDir . '/phrity/util-errorhandler/src'),
    'Phrity\\Net\\' => array($vendorDir . '/phrity/net-stream/src', $vendorDir . '/phrity/net-uri/src'),
    'Phrity\\Comparison\\' => array($vendorDir . '/phrity/comparison/src'),
    'Mdanter\\Ecc\\' => array($vendorDir . '/paragonie/ecc/src'),
    'FG\\' => array($vendorDir . '/genkgo/php-asn1/lib'),
    'Elliptic\\' => array($vendorDir . '/simplito/elliptic-php/lib'),
    'ChaCha20\\' => array($vendorDir . '/leigh/chacha20/lib'),
    'BitWasp\\Bech32\\' => array($vendorDir . '/bitwasp/bech32/src'),
    'BN\\' => array($vendorDir . '/simplito/bn-php/lib'),
    'BI\\' => array($vendorDir . '/simplito/bigint-wrapper-php/lib'),
);
