<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit98e7dbb8b0f2ba2cb8c82f78a0693b49
{
    public static $files = array (
        '3109cb1a231dcd04bee1f9f620d46975' => __DIR__ . '/..' . '/paragonie/sodium_compat/autoload.php',
        'a626201e4406003b96eee958a069f504' => __DIR__ . '/..' . '/bitwasp/bech32/src/bech32.php',
        '464c6d48a71239da948e8c8f195c0707' => __DIR__ . '/..' . '/leigh/chacha20/lib/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        's' => 
        array (
            'swentel\\nostr\\' => 14,
        ),
        'W' => 
        array (
            'WebSocket\\' => 10,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Phrity\\Util\\' => 12,
            'Phrity\\Net\\' => 11,
            'Phrity\\Comparison\\' => 18,
        ),
        'M' => 
        array (
            'Mdanter\\Ecc\\' => 12,
        ),
        'F' => 
        array (
            'FG\\' => 3,
        ),
        'E' => 
        array (
            'Elliptic\\' => 9,
        ),
        'C' => 
        array (
            'ChaCha20\\' => 9,
        ),
        'B' => 
        array (
            'BitWasp\\Bech32\\' => 15,
            'BN\\' => 3,
            'BI\\' => 3,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'swentel\\nostr\\' => 
        array (
            0 => __DIR__ . '/..' . '/swentel/nostr-php/src',
        ),
        'WebSocket\\' => 
        array (
            0 => __DIR__ . '/..' . '/phrity/websocket/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Phrity\\Util\\' => 
        array (
            0 => __DIR__ . '/..' . '/phrity/util-errorhandler/src',
        ),
        'Phrity\\Net\\' => 
        array (
            0 => __DIR__ . '/..' . '/phrity/net-stream/src',
            1 => __DIR__ . '/..' . '/phrity/net-uri/src',
        ),
        'Phrity\\Comparison\\' => 
        array (
            0 => __DIR__ . '/..' . '/phrity/comparison/src',
        ),
        'Mdanter\\Ecc\\' => 
        array (
            0 => __DIR__ . '/..' . '/paragonie/ecc/src',
        ),
        'FG\\' => 
        array (
            0 => __DIR__ . '/..' . '/genkgo/php-asn1/lib',
        ),
        'Elliptic\\' => 
        array (
            0 => __DIR__ . '/..' . '/simplito/elliptic-php/lib',
        ),
        'ChaCha20\\' => 
        array (
            0 => __DIR__ . '/..' . '/leigh/chacha20/lib',
        ),
        'BitWasp\\Bech32\\' => 
        array (
            0 => __DIR__ . '/..' . '/bitwasp/bech32/src',
        ),
        'BN\\' => 
        array (
            0 => __DIR__ . '/..' . '/simplito/bn-php/lib',
        ),
        'BI\\' => 
        array (
            0 => __DIR__ . '/..' . '/simplito/bigint-wrapper-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit98e7dbb8b0f2ba2cb8c82f78a0693b49::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit98e7dbb8b0f2ba2cb8c82f78a0693b49::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit98e7dbb8b0f2ba2cb8c82f78a0693b49::$classMap;

        }, null, ClassLoader::class);
    }
}
