<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bitwasp/bech32' => array(
            'pretty_version' => 'v0.0.1',
            'version' => '0.0.1.0',
            'reference' => 'e1ea58c848a4ec59d81b697b3dfe9cc99968d0e7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bitwasp/bech32',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'genkgo/php-asn1' => array(
            'pretty_version' => 'v2.8.0',
            'version' => '2.8.0.0',
            'reference' => '4de712c68bbf51c00551cb45f55642e30fed1fdb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../genkgo/php-asn1',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'leigh/chacha20' => array(
            'pretty_version' => '0.2.0',
            'version' => '0.2.0.0',
            'reference' => '7aeffd53228be384b4a8986c9a8d9578acb171a4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../leigh/chacha20',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/ecc' => array(
            'pretty_version' => 'v2.5.0',
            'version' => '2.5.0.0',
            'reference' => 'd25bd2aab9b1205db1cf3aa3e83531d4549377bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/ecc',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/sodium_compat' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'a673d5f310477027cead2e2f2b6db5d8368157cb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/sodium_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phrity/comparison' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => 'aedd44d59db08de7d6c31812d1490c22aab35c92',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phrity/comparison',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phrity/net-stream' => array(
            'pretty_version' => '2.3.1',
            'version' => '2.3.1.0',
            'reference' => 'c621bb3108a5a02bba64df2e5f0cd7ada02665b5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phrity/net-stream',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phrity/net-uri' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '08de4cf07e439c4708f572249659f09198ac99f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phrity/net-uri',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phrity/util-errorhandler' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '9825f15ef9b4a93252ce53ca8962278832d834da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phrity/util-errorhandler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phrity/websocket' => array(
            'pretty_version' => '3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'df3b4dbe3a8741159ae5cb5735476ebc4813d909',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phrity/websocket',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'simplito/bigint-wrapper-php' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'cf21ec76d33f103add487b3eadbd9f5033a25930',
            'type' => 'library',
            'install_path' => __DIR__ . '/../simplito/bigint-wrapper-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'simplito/bn-php' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => '83446756a81720eacc2ffb87ff97958431451fd6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../simplito/bn-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'simplito/elliptic-php' => array(
            'pretty_version' => '1.0.12',
            'version' => '1.0.12.0',
            'reference' => 'be321666781be2be2c89c79c43ffcac834bc8868',
            'type' => 'library',
            'install_path' => __DIR__ . '/../simplito/elliptic-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'swentel/nostr-php' => array(
            'pretty_version' => '1.9.2',
            'version' => '1.9.2.0',
            'reference' => '8fb8337354b2e9d48a901276c7814d7fa7b25653',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swentel/nostr-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
